/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.shared;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;

public class Security {
    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=Circle-Token")
    public String apiKeyHeader;
    public Security withApiKeyHeader(String apiKeyHeader) {
        this.apiKeyHeader = apiKeyHeader;
        return this;
    }
    
    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=query,name=circle-token")
    public String apiKeyQuery;
    public Security withApiKeyQuery(String apiKeyQuery) {
        this.apiKeyQuery = apiKeyQuery;
        return this;
    }
    
    @SpeakeasyMetadata("security:scheme=true,type=http,subtype=basic")
    public SchemeBasicAuth basicAuth;
    public Security withBasicAuth(SchemeBasicAuth basicAuth) {
        this.basicAuth = basicAuth;
        return this;
    }
    
    public Security(){}
}
