/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ApprovePendingApprovalJobByIdResponse {
    
    public String contentType;

    public ApprovePendingApprovalJobByIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A confirmation message.
     */
    
    public ApprovePendingApprovalJobByIdMessageResponse messageResponse;

    public ApprovePendingApprovalJobByIdResponse withMessageResponse(ApprovePendingApprovalJobByIdMessageResponse messageResponse) {
        this.messageResponse = messageResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ApprovePendingApprovalJobByIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ApprovePendingApprovalJobByIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public ApprovePendingApprovalJobByIdDefaultApplicationJSON approvePendingApprovalJobByIdDefaultApplicationJSONObject;

    public ApprovePendingApprovalJobByIdResponse withApprovePendingApprovalJobByIdDefaultApplicationJSONObject(ApprovePendingApprovalJobByIdDefaultApplicationJSON approvePendingApprovalJobByIdDefaultApplicationJSONObject) {
        this.approvePendingApprovalJobByIdDefaultApplicationJSONObject = approvePendingApprovalJobByIdDefaultApplicationJSONObject;
        return this;
    }
    
    public ApprovePendingApprovalJobByIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
