/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ApprovePendingApprovalJobByIdRequest {
    /**
     * The ID of the job being approved.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=approval_request_id")
    public String approvalRequestId;
    public ApprovePendingApprovalJobByIdRequest withApprovalRequestId(String approvalRequestId) {
        this.approvalRequestId = approvalRequestId;
        return this;
    }
    
    /**
     * The unique ID of the workflow.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;
    public ApprovePendingApprovalJobByIdRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public ApprovePendingApprovalJobByIdRequest(@JsonProperty("approval_request_id") String approvalRequestId, @JsonProperty("id") String id) {
        this.approvalRequestId = approvalRequestId;
        this.id = id;
  }
}
