/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CancelJobResponse {
    
    public String contentType;
    public CancelJobResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public CancelJobMessageResponse messageResponse;
    public CancelJobResponse withMessageResponse(CancelJobMessageResponse messageResponse) {
        this.messageResponse = messageResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public CancelJobResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public CancelJobResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public CancelJobDefaultApplicationJSON cancelJobDefaultApplicationJSONObject;
    public CancelJobResponse withCancelJobDefaultApplicationJSONObject(CancelJobDefaultApplicationJSON cancelJobDefaultApplicationJSONObject) {
        this.cancelJobDefaultApplicationJSONObject = cancelJobDefaultApplicationJSONObject;
        return this;
    }
    
    public CancelJobResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
