/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CancelWorkflowResponse {
    
    public String contentType;

    public CancelWorkflowResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A confirmation message.
     */
    
    public CancelWorkflowMessageResponse messageResponse;

    public CancelWorkflowResponse withMessageResponse(CancelWorkflowMessageResponse messageResponse) {
        this.messageResponse = messageResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public CancelWorkflowResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CancelWorkflowResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public CancelWorkflowDefaultApplicationJSON cancelWorkflowDefaultApplicationJSONObject;

    public CancelWorkflowResponse withCancelWorkflowDefaultApplicationJSONObject(CancelWorkflowDefaultApplicationJSON cancelWorkflowDefaultApplicationJSONObject) {
        this.cancelWorkflowDefaultApplicationJSONObject = cancelWorkflowDefaultApplicationJSONObject;
        return this;
    }
    
    public CancelWorkflowResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
