/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ContinuePipelineRequestBody {
    /**
     * A configuration string for the pipeline.
     */
    @JsonProperty("configuration")
    public String configuration;

    public ContinuePipelineRequestBody withConfiguration(String configuration) {
        this.configuration = configuration;
        return this;
    }
    
    /**
     * A pipeline continuation key.
     */
    @JsonProperty("continuation-key")
    public String continuationKey;

    public ContinuePipelineRequestBody withContinuationKey(String continuationKey) {
        this.continuationKey = continuationKey;
        return this;
    }
    
    /**
     * An object containing pipeline parameters and their values.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parameters")
    public java.util.Map<String, Object> parameters;

    public ContinuePipelineRequestBody withParameters(java.util.Map<String, Object> parameters) {
        this.parameters = parameters;
        return this;
    }
    
    public ContinuePipelineRequestBody(@JsonProperty("configuration") String configuration, @JsonProperty("continuation-key") String continuationKey) {
        this.configuration = configuration;
        this.continuationKey = continuationKey;
  }
}
