/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateCheckoutKeyCheckoutKeyInput {
    /**
     * The type of checkout key to create. This may be either `deploy-key` or `user-key`.
     */
    @JsonProperty("type")
    public CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputTypeEnum type;
    public CreateCheckoutKeyCheckoutKeyInput withType(CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputTypeEnum type) {
        this.type = type;
        return this;
    }
    
    public CreateCheckoutKeyCheckoutKeyInput(@JsonProperty("type") CreateCheckoutKeyCheckoutKeyInputCheckoutKeyInputTypeEnum type) {
        this.type = type;
  }
}
