/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateScheduleResponse {
    
    public String contentType;

    public CreateScheduleResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A schedule object.
     */
    
    public CreateScheduleSchedule schedule;

    public CreateScheduleResponse withSchedule(CreateScheduleSchedule schedule) {
        this.schedule = schedule;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateScheduleResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateScheduleResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public CreateScheduleDefaultApplicationJSON createScheduleDefaultApplicationJSONObject;

    public CreateScheduleResponse withCreateScheduleDefaultApplicationJSONObject(CreateScheduleDefaultApplicationJSON createScheduleDefaultApplicationJSONObject) {
        this.createScheduleDefaultApplicationJSONObject = createScheduleDefaultApplicationJSONObject;
        return this;
    }
    
    public CreateScheduleResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
