/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateContextRequestBodyOwner1TypeEnum - The type of the owner. Defaults to "organization". Accounts are only used as context owners in server.
 */
public enum CreateContextRequestBodyOwner1TypeEnum {
    ACCOUNT("account"),
    ORGANIZATION("organization");

    @JsonValue
    public final String value;

    private CreateContextRequestBodyOwner1TypeEnum(String value) {
        this.value = value;
    }
}
