/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateScheduleCreateScheduleParameters - The parameters for a create schedule request
 */
public class CreateScheduleCreateScheduleParameters {
    /**
     * The attribution-actor of the scheduled pipeline.
     */
    @JsonProperty("attribution-actor")
    public CreateScheduleCreateScheduleParametersAttributionActor attributionActor;

    public CreateScheduleCreateScheduleParameters withAttributionActor(CreateScheduleCreateScheduleParametersAttributionActor attributionActor) {
        this.attributionActor = attributionActor;
        return this;
    }
    
    /**
     * Description of the schedule.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public CreateScheduleCreateScheduleParameters withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * Name of the schedule.
     */
    @JsonProperty("name")
    public String name;

    public CreateScheduleCreateScheduleParameters withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Pipeline parameters represented as key-value pairs. Must contain branch or tag.
     */
    @JsonProperty("parameters")
    public java.util.Map<String, Object> parameters;

    public CreateScheduleCreateScheduleParameters withParameters(java.util.Map<String, Object> parameters) {
        this.parameters = parameters;
        return this;
    }
    
    /**
     * Timetable that specifies when a schedule triggers.
     */
    @JsonProperty("timetable")
    public Object timetable;

    public CreateScheduleCreateScheduleParameters withTimetable(Object timetable) {
        this.timetable = timetable;
        return this;
    }
    
    public CreateScheduleCreateScheduleParameters(@JsonProperty("attribution-actor") CreateScheduleCreateScheduleParametersAttributionActor attributionActor, @JsonProperty("name") String name, @JsonProperty("parameters") java.util.Map<String, Object> parameters, @JsonProperty("timetable") Object timetable) {
        this.attributionActor = attributionActor;
        this.name = name;
        this.parameters = parameters;
        this.timetable = timetable;
  }
}
