/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateScheduleCreateScheduleParametersTimetable1 - Timetable that specifies when a schedule triggers.
 */
public class CreateScheduleCreateScheduleParametersTimetable1 {
    /**
     * Days in a month in which the schedule triggers. This is mutually exclusive with days in a week.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("days-of-month")
    public Long[] daysOfMonth;
    public CreateScheduleCreateScheduleParametersTimetable1 withDaysOfMonth(Long[] daysOfMonth) {
        this.daysOfMonth = daysOfMonth;
        return this;
    }
    
    /**
     * Days in a week in which the schedule triggers.
     */
    @JsonProperty("days-of-week")
    public CreateScheduleCreateScheduleParametersTimetable1DaysOfWeekEnum[] daysOfWeek;
    public CreateScheduleCreateScheduleParametersTimetable1 withDaysOfWeek(CreateScheduleCreateScheduleParametersTimetable1DaysOfWeekEnum[] daysOfWeek) {
        this.daysOfWeek = daysOfWeek;
        return this;
    }
    
    /**
     * Hours in a day in which the schedule triggers.
     */
    @JsonProperty("hours-of-day")
    public Long[] hoursOfDay;
    public CreateScheduleCreateScheduleParametersTimetable1 withHoursOfDay(Long[] hoursOfDay) {
        this.hoursOfDay = hoursOfDay;
        return this;
    }
    
    /**
     * Months in which the schedule triggers.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("months")
    public CreateScheduleCreateScheduleParametersTimetable1MonthsEnum[] months;
    public CreateScheduleCreateScheduleParametersTimetable1 withMonths(CreateScheduleCreateScheduleParametersTimetable1MonthsEnum[] months) {
        this.months = months;
        return this;
    }
    
    /**
     * Number of times a schedule triggers per hour, value must be between 1 and 60
     */
    @JsonProperty("per-hour")
    public Long perHour;
    public CreateScheduleCreateScheduleParametersTimetable1 withPerHour(Long perHour) {
        this.perHour = perHour;
        return this;
    }
    
    public CreateScheduleCreateScheduleParametersTimetable1(@JsonProperty("days-of-week") CreateScheduleCreateScheduleParametersTimetable1DaysOfWeekEnum[] daysOfWeek, @JsonProperty("hours-of-day") Long[] hoursOfDay, @JsonProperty("per-hour") Long perHour) {
        this.daysOfWeek = daysOfWeek;
        this.hoursOfDay = hoursOfDay;
        this.perHour = perHour;
  }
}
