/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateContextRequestBodyOwner2Type - The type of owner. Defaults to "organization". Accounts are only used as context owners in server and must be specified by an id instead of a slug.
 */
public enum CreateContextRequestBodyOwner2Type {
    ORGANIZATION("organization");

    @JsonValue
    public final String value;

    private CreateContextRequestBodyOwner2Type(String value) {
        this.value = value;
    }
}
