/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CreateWebhookResponse {
    
    public String contentType;
    public CreateWebhookResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public CreateWebhookResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public CreateWebhookResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A webhook
     */
    
    public CreateWebhookWebhook webhook;
    public CreateWebhookResponse withWebhook(CreateWebhookWebhook webhook) {
        this.webhook = webhook;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public CreateWebhookDefaultApplicationJSON createWebhookDefaultApplicationJSONObject;
    public CreateWebhookResponse withCreateWebhookDefaultApplicationJSONObject(CreateWebhookDefaultApplicationJSON createWebhookDefaultApplicationJSONObject) {
        this.createWebhookDefaultApplicationJSONObject = createWebhookDefaultApplicationJSONObject;
        return this;
    }
    
    public CreateWebhookResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
