/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateWebhookRequestBodyScopeType - Type of the scope being used
 */
public enum CreateWebhookRequestBodyScopeType {
    PROJECT("project");

    @JsonValue
    public final String value;

    private CreateWebhookRequestBodyScopeType(String value) {
        this.value = value;
    }
}
