/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateScheduleScheduleUser - The attribution actor who will run the scheduled pipeline.
 */
public class CreateScheduleScheduleUser {
    /**
     * The unique ID of the user.
     */
    @JsonProperty("id")
    public String id;

    public CreateScheduleScheduleUser withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The login information for the user on the VCS.
     */
    @JsonProperty("login")
    public String login;

    public CreateScheduleScheduleUser withLogin(String login) {
        this.login = login;
        return this;
    }
    
    /**
     * The name of the user.
     */
    @JsonProperty("name")
    public String name;

    public CreateScheduleScheduleUser withName(String name) {
        this.name = name;
        return this;
    }
    
    public CreateScheduleScheduleUser(@JsonProperty("id") String id, @JsonProperty("login") String login, @JsonProperty("name") String name) {
        this.id = id;
        this.login = login;
        this.name = name;
  }
}
