/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateScheduleCreateScheduleParametersAttributionActorEnum - The attribution-actor of the scheduled pipeline.
 */
public enum CreateScheduleCreateScheduleParametersAttributionActorEnum {
    CURRENT("current"),
    SYSTEM("system");

    @JsonValue
    public final String value;

    private CreateScheduleCreateScheduleParametersAttributionActorEnum(String value) {
        this.value = value;
    }
}
