/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DeleteCheckoutKeyResponse {
    
    public String contentType;
    public DeleteCheckoutKeyResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A confirmation message.
     */
    
    public DeleteCheckoutKeyMessageResponse messageResponse;
    public DeleteCheckoutKeyResponse withMessageResponse(DeleteCheckoutKeyMessageResponse messageResponse) {
        this.messageResponse = messageResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public DeleteCheckoutKeyResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public DeleteCheckoutKeyResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public DeleteCheckoutKeyDefaultApplicationJSON deleteCheckoutKeyDefaultApplicationJSONObject;
    public DeleteCheckoutKeyResponse withDeleteCheckoutKeyDefaultApplicationJSONObject(DeleteCheckoutKeyDefaultApplicationJSON deleteCheckoutKeyDefaultApplicationJSONObject) {
        this.deleteCheckoutKeyDefaultApplicationJSONObject = deleteCheckoutKeyDefaultApplicationJSONObject;
        return this;
    }
    
    public DeleteCheckoutKeyResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
