/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DeleteWebhookResponse {
    
    public String contentType;
    public DeleteWebhookResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A confirmation message
     */
    
    public DeleteWebhookMessageResponse messageResponse;
    public DeleteWebhookResponse withMessageResponse(DeleteWebhookMessageResponse messageResponse) {
        this.messageResponse = messageResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public DeleteWebhookResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public DeleteWebhookResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public DeleteWebhookDefaultApplicationJSON deleteWebhookDefaultApplicationJSONObject;
    public DeleteWebhookResponse withDeleteWebhookDefaultApplicationJSONObject(DeleteWebhookDefaultApplicationJSON deleteWebhookDefaultApplicationJSONObject) {
        this.deleteWebhookDefaultApplicationJSONObject = deleteWebhookDefaultApplicationJSONObject;
        return this;
    }
    
    public DeleteWebhookResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
