/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DeleteContextRequest {
    /**
     * ID of the context (UUID)
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=context-id")
    public String contextId;

    public DeleteContextRequest withContextId(String contextId) {
        this.contextId = contextId;
        return this;
    }
    
    public DeleteContextRequest(@JsonProperty("context-id") String contextId) {
        this.contextId = contextId;
  }
}
