/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DeleteEnvironmentVariableFromContextResponse {
    
    public String contentType;
    public DeleteEnvironmentVariableFromContextResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A confirmation message
     */
    
    public DeleteEnvironmentVariableFromContextMessageResponse messageResponse;
    public DeleteEnvironmentVariableFromContextResponse withMessageResponse(DeleteEnvironmentVariableFromContextMessageResponse messageResponse) {
        this.messageResponse = messageResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public DeleteEnvironmentVariableFromContextResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public DeleteEnvironmentVariableFromContextResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public DeleteEnvironmentVariableFromContextDefaultApplicationJSON deleteEnvironmentVariableFromContextDefaultApplicationJSONObject;
    public DeleteEnvironmentVariableFromContextResponse withDeleteEnvironmentVariableFromContextDefaultApplicationJSONObject(DeleteEnvironmentVariableFromContextDefaultApplicationJSON deleteEnvironmentVariableFromContextDefaultApplicationJSONObject) {
        this.deleteEnvironmentVariableFromContextDefaultApplicationJSONObject = deleteEnvironmentVariableFromContextDefaultApplicationJSONObject;
        return this;
    }
    
    public DeleteEnvironmentVariableFromContextResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
