/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetAllInsightsBranchesResponse {
    
    public String contentType;

    public GetAllInsightsBranchesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetAllInsightsBranchesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetAllInsightsBranchesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A list of branches for a project
     */
    
    public Object getAllInsightsBranches200ApplicationJSONAny;

    public GetAllInsightsBranchesResponse withGetAllInsightsBranches200ApplicationJSONAny(Object getAllInsightsBranches200ApplicationJSONAny) {
        this.getAllInsightsBranches200ApplicationJSONAny = getAllInsightsBranches200ApplicationJSONAny;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetAllInsightsBranchesDefaultApplicationJSON getAllInsightsBranchesDefaultApplicationJSONObject;

    public GetAllInsightsBranchesResponse withGetAllInsightsBranchesDefaultApplicationJSONObject(GetAllInsightsBranchesDefaultApplicationJSON getAllInsightsBranchesDefaultApplicationJSONObject) {
        this.getAllInsightsBranchesDefaultApplicationJSONObject = getAllInsightsBranchesDefaultApplicationJSONObject;
        return this;
    }
    
    public GetAllInsightsBranchesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
