/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetAllInsightsBranchesRequest {
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project-slug")
    public String projectSlug;

    public GetAllInsightsBranchesRequest withProjectSlug(String projectSlug) {
        this.projectSlug = projectSlug;
        return this;
    }
    
    /**
     * The name of a workflow. If not passed we will scope the API call to the project.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=workflow-name")
    public String workflowName;

    public GetAllInsightsBranchesRequest withWorkflowName(String workflowName) {
        this.workflowName = workflowName;
        return this;
    }
    
    public GetAllInsightsBranchesRequest(@JsonProperty("project-slug") String projectSlug) {
        this.projectSlug = projectSlug;
  }
}
