/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetCheckoutKeyRequest {
    /**
     * An SSH key fingerprint.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=fingerprint")
    public String fingerprint;

    public GetCheckoutKeyRequest withFingerprint(String fingerprint) {
        this.fingerprint = fingerprint;
        return this;
    }
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project-slug")
    public String projectSlug;

    public GetCheckoutKeyRequest withProjectSlug(String projectSlug) {
        this.projectSlug = projectSlug;
        return this;
    }
    
    public GetCheckoutKeyRequest(@JsonProperty("fingerprint") String fingerprint, @JsonProperty("project-slug") String projectSlug) {
        this.fingerprint = fingerprint;
        this.projectSlug = projectSlug;
  }
}
