/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetCollaborationsResponse {
    /**
     * Collaborations
     */
    
    public GetCollaborationsCollaboration[] collaborations;
    public GetCollaborationsResponse withCollaborations(GetCollaborationsCollaboration[] collaborations) {
        this.collaborations = collaborations;
        return this;
    }
    
    
    public String contentType;
    public GetCollaborationsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetCollaborationsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetCollaborationsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetCollaborationsDefaultApplicationJSON getCollaborationsDefaultApplicationJSONObject;
    public GetCollaborationsResponse withGetCollaborationsDefaultApplicationJSONObject(GetCollaborationsDefaultApplicationJSON getCollaborationsDefaultApplicationJSONObject) {
        this.getCollaborationsDefaultApplicationJSONObject = getCollaborationsDefaultApplicationJSONObject;
        return this;
    }
    
    public GetCollaborationsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
