/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetFlakyTests200ApplicationJSON - Flaky tests response
 */
public class GetFlakyTests200ApplicationJSON {
    /**
     * A list of all instances of flakes. Note that a test is no longer considered flaky after 2 weeks have passed without a flake. Each flake resets this timer.
     */
    @JsonProperty("flaky-tests")
    public GetFlakyTests200ApplicationJSONFlakyTests[] flakyTests;

    public GetFlakyTests200ApplicationJSON withFlakyTests(GetFlakyTests200ApplicationJSONFlakyTests[] flakyTests) {
        this.flakyTests = flakyTests;
        return this;
    }
    
    /**
     * A count of unique tests that have failed. If your project has N tests that have flaked multiple times each, this will be equal to N.
     */
    @JsonProperty("total-flaky-tests")
    public Double totalFlakyTests;

    public GetFlakyTests200ApplicationJSON withTotalFlakyTests(Double totalFlakyTests) {
        this.totalFlakyTests = totalFlakyTests;
        return this;
    }
    
    public GetFlakyTests200ApplicationJSON(@JsonProperty("flaky-tests") GetFlakyTests200ApplicationJSONFlakyTests[] flakyTests, @JsonProperty("total-flaky-tests") Double totalFlakyTests) {
        this.flakyTests = flakyTests;
        this.totalFlakyTests = totalFlakyTests;
  }
}
