/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetJobTimeseriesGranularity - The granularity for which to query timeseries data.
 */
public enum GetJobTimeseriesGranularity {
    DAILY("daily"),
    HOURLY("hourly");

    @JsonValue
    public final String value;

    private GetJobTimeseriesGranularity(String value) {
        this.value = value;
    }
}
