/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetJobTimeseriesResponse {
    
    public String contentType;
    public GetJobTimeseriesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetJobTimeseriesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetJobTimeseriesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * An array of timeseries data, one entry per job.
     */
    
    public GetJobTimeseries200ApplicationJSON getJobTimeseries200ApplicationJSONObject;
    public GetJobTimeseriesResponse withGetJobTimeseries200ApplicationJSONObject(GetJobTimeseries200ApplicationJSON getJobTimeseries200ApplicationJSONObject) {
        this.getJobTimeseries200ApplicationJSONObject = getJobTimeseries200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetJobTimeseriesDefaultApplicationJSON getJobTimeseriesDefaultApplicationJSONObject;
    public GetJobTimeseriesResponse withGetJobTimeseriesDefaultApplicationJSONObject(GetJobTimeseriesDefaultApplicationJSON getJobTimeseriesDefaultApplicationJSONObject) {
        this.getJobTimeseriesDefaultApplicationJSONObject = getJobTimeseriesDefaultApplicationJSONObject;
        return this;
    }
    
    public GetJobTimeseriesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
