/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetJobArtifactsArtifactListResponseArtifact - An artifact
 */
public class GetJobArtifactsArtifactListResponseArtifact {
    /**
     * The index of the node that stored the artifact.
     */
    @JsonProperty("node_index")
    public Long nodeIndex;

    public GetJobArtifactsArtifactListResponseArtifact withNodeIndex(Long nodeIndex) {
        this.nodeIndex = nodeIndex;
        return this;
    }
    
    /**
     * The artifact path.
     */
    @JsonProperty("path")
    public String path;

    public GetJobArtifactsArtifactListResponseArtifact withPath(String path) {
        this.path = path;
        return this;
    }
    
    /**
     * The URL to download the artifact contents.
     */
    @JsonProperty("url")
    public String url;

    public GetJobArtifactsArtifactListResponseArtifact withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public GetJobArtifactsArtifactListResponseArtifact(@JsonProperty("node_index") Long nodeIndex, @JsonProperty("path") String path, @JsonProperty("url") String url) {
        this.nodeIndex = nodeIndex;
        this.path = path;
        this.url = url;
  }
}
