/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetJobDetailsJobDetailsPipeline - Info about a pipeline the job is a part of.
 */
public class GetJobDetailsJobDetailsPipeline {
    /**
     * The unique ID of the pipeline.
     */
    @JsonProperty("id")
    public String id;

    public GetJobDetailsJobDetailsPipeline withId(String id) {
        this.id = id;
        return this;
    }
    
    public GetJobDetailsJobDetailsPipeline(@JsonProperty("id") String id) {
        this.id = id;
  }
}
