/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetJobDetailsJobDetailsProject - Information about a project.
 */
public class GetJobDetailsJobDetailsProject {
    /**
     * URL to the repository hosting the project's code
     */
    @JsonProperty("external_url")
    public String externalUrl;
    public GetJobDetailsJobDetailsProject withExternalUrl(String externalUrl) {
        this.externalUrl = externalUrl;
        return this;
    }
    
    @JsonProperty("id")
    public String id;
    public GetJobDetailsJobDetailsProject withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The name of the project
     */
    @JsonProperty("name")
    public String name;
    public GetJobDetailsJobDetailsProject withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     */
    @JsonProperty("slug")
    public String slug;
    public GetJobDetailsJobDetailsProject withSlug(String slug) {
        this.slug = slug;
        return this;
    }
    
    public GetJobDetailsJobDetailsProject(@JsonProperty("external_url") String externalUrl, @JsonProperty("id") String id, @JsonProperty("name") String name, @JsonProperty("slug") String slug) {
        this.externalUrl = externalUrl;
        this.id = id;
        this.name = name;
        this.slug = slug;
  }
}
