/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetJobDetailsJobDetailsContexts - Information about the context.
 */
public class GetJobDetailsJobDetailsContexts {
    /**
     * The name of the context.
     */
    @JsonProperty("name")
    public String name;

    public GetJobDetailsJobDetailsContexts withName(String name) {
        this.name = name;
        return this;
    }
    
    public GetJobDetailsJobDetailsContexts(@JsonProperty("name") String name) {
        this.name = name;
  }
}
