/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetJobArtifactsRequest {
    /**
     * The number of the job.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=job-number")
    public Object jobNumber;
    public GetJobArtifactsRequest withJobNumber(Object jobNumber) {
        this.jobNumber = jobNumber;
        return this;
    }
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project-slug")
    public String projectSlug;
    public GetJobArtifactsRequest withProjectSlug(String projectSlug) {
        this.projectSlug = projectSlug;
        return this;
    }
    
    public GetJobArtifactsRequest(@JsonProperty("job-number") Object jobNumber, @JsonProperty("project-slug") String projectSlug) {
        this.jobNumber = jobNumber;
        this.projectSlug = projectSlug;
  }
}
