/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetOrgSummaryData200ApplicationJSONOrgData - Aggregated metrics for an org, with trends.
 */
public class GetOrgSummaryData200ApplicationJSONOrgData {
    /**
     * Metrics for a single org metrics.
     */
    @JsonProperty("metrics")
    public GetOrgSummaryData200ApplicationJSONOrgDataMetrics metrics;

    public GetOrgSummaryData200ApplicationJSONOrgData withMetrics(GetOrgSummaryData200ApplicationJSONOrgDataMetrics metrics) {
        this.metrics = metrics;
        return this;
    }
    
    /**
     * Trends for a single org.
     */
    @JsonProperty("trends")
    public GetOrgSummaryData200ApplicationJSONOrgDataTrends trends;

    public GetOrgSummaryData200ApplicationJSONOrgData withTrends(GetOrgSummaryData200ApplicationJSONOrgDataTrends trends) {
        this.trends = trends;
        return this;
    }
    
    public GetOrgSummaryData200ApplicationJSONOrgData(@JsonProperty("metrics") GetOrgSummaryData200ApplicationJSONOrgDataMetrics metrics, @JsonProperty("trends") GetOrgSummaryData200ApplicationJSONOrgDataTrends trends) {
        this.metrics = metrics;
        this.trends = trends;
  }
}
