/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetOrgSummaryDataResponse {
    
    public String contentType;

    public GetOrgSummaryDataResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOrgSummaryDataResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOrgSummaryDataResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * summary metrics with trends for an entire org and it's projects.
     */
    
    public GetOrgSummaryData200ApplicationJSON getOrgSummaryData200ApplicationJSONObject;

    public GetOrgSummaryDataResponse withGetOrgSummaryData200ApplicationJSONObject(GetOrgSummaryData200ApplicationJSON getOrgSummaryData200ApplicationJSONObject) {
        this.getOrgSummaryData200ApplicationJSONObject = getOrgSummaryData200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetOrgSummaryDataDefaultApplicationJSON getOrgSummaryDataDefaultApplicationJSONObject;

    public GetOrgSummaryDataResponse withGetOrgSummaryDataDefaultApplicationJSONObject(GetOrgSummaryDataDefaultApplicationJSON getOrgSummaryDataDefaultApplicationJSONObject) {
        this.getOrgSummaryDataDefaultApplicationJSONObject = getOrgSummaryDataDefaultApplicationJSONObject;
        return this;
    }
    
    public GetOrgSummaryDataResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
