/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetOrgSummaryDataRequest {
    /**
     * Org slug in the form `vcs-slug/org-name`. The `/` characters may be URL-escaped.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=org-slug")
    public String orgSlug;

    public GetOrgSummaryDataRequest withOrgSlug(String orgSlug) {
        this.orgSlug = orgSlug;
        return this;
    }
    
    /**
     * List of project names.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=project-names")
    public java.util.Map<String, Object> projectNames;

    public GetOrgSummaryDataRequest withProjectNames(java.util.Map<String, Object> projectNames) {
        this.projectNames = projectNames;
        return this;
    }
    
    /**
     * The time window used to calculate summary metrics.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reporting-window")
    public GetOrgSummaryDataReportingWindow reportingWindow;

    public GetOrgSummaryDataRequest withReportingWindow(GetOrgSummaryDataReportingWindow reportingWindow) {
        this.reportingWindow = reportingWindow;
        return this;
    }
    
    public GetOrgSummaryDataRequest(@JsonProperty("org-slug") String orgSlug) {
        this.orgSlug = orgSlug;
  }
}
