/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;



/**
 * GetOrgSummaryDataProjectNames - List of project names.
 */
public class GetOrgSummaryDataProjectNames {
    public GetOrgSummaryDataProjectNames(){}
}
