/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;



/**
 * GetProjectWorkflowsPageDataWorkflowNames - The names of workflows to include in workflow-level metrics.
 */
public class GetProjectWorkflowsPageDataWorkflowNames {
    public GetProjectWorkflowsPageDataWorkflowNames(){}
}
