/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowData {
    /**
     * Metrics aggregated across a workflow or branchfor a project.
     */
    @JsonProperty("metrics")
    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataMetrics metrics;

    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowData withMetrics(GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataMetrics metrics) {
        this.metrics = metrics;
        return this;
    }
    
    /**
     * Trends aggregated across a workflow or branch for a project.
     */
    @JsonProperty("trends")
    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataTrends trends;

    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowData withTrends(GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataTrends trends) {
        this.trends = trends;
        return this;
    }
    
    /**
     * The name of the workflow.
     */
    @JsonProperty("workflow_name")
    public String workflowName;

    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowData withWorkflowName(String workflowName) {
        this.workflowName = workflowName;
        return this;
    }
    
    public GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowData(@JsonProperty("metrics") GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataMetrics metrics, @JsonProperty("trends") GetProjectWorkflowsPageData200ApplicationJSONProjectWorkflowDataTrends trends, @JsonProperty("workflow_name") String workflowName) {
        this.metrics = metrics;
        this.trends = trends;
        this.workflowName = workflowName;
  }
}
