/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetProjectWorkflowsPageData200ApplicationJSONProjectData - Metrics and trends data aggregated for a given project.
 */
public class GetProjectWorkflowsPageData200ApplicationJSONProjectData {
    /**
     * Metrics aggregated across all workflows and branches for a project.
     */
    @JsonProperty("metrics")
    public GetProjectWorkflowsPageData200ApplicationJSONProjectDataMetrics metrics;
    public GetProjectWorkflowsPageData200ApplicationJSONProjectData withMetrics(GetProjectWorkflowsPageData200ApplicationJSONProjectDataMetrics metrics) {
        this.metrics = metrics;
        return this;
    }
    
    /**
     * Metric trends aggregated across all workflows and branches for a project.
     */
    @JsonProperty("trends")
    public GetProjectWorkflowsPageData200ApplicationJSONProjectDataTrends trends;
    public GetProjectWorkflowsPageData200ApplicationJSONProjectData withTrends(GetProjectWorkflowsPageData200ApplicationJSONProjectDataTrends trends) {
        this.trends = trends;
        return this;
    }
    
    public GetProjectWorkflowsPageData200ApplicationJSONProjectData(@JsonProperty("metrics") GetProjectWorkflowsPageData200ApplicationJSONProjectDataMetrics metrics, @JsonProperty("trends") GetProjectWorkflowsPageData200ApplicationJSONProjectDataTrends trends) {
        this.metrics = metrics;
        this.trends = trends;
  }
}
