/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetProjectWorkflowRuns200ApplicationJSONItemsStatusEnum - Workflow status.
 */
public enum GetProjectWorkflowRuns200ApplicationJSONItemsStatusEnum {
    SUCCESS("success"),
    FAILED("failed"),
    ERROR("error"),
    CANCELED("canceled"),
    UNAUTHORIZED("unauthorized");

    @JsonValue
    public final String value;

    private GetProjectWorkflowRuns200ApplicationJSONItemsStatusEnum(String value) {
        this.value = value;
    }
}
