/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetPipelineConfigByIdResponse {
    
    public String contentType;
    public GetPipelineConfigByIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * The configuration strings for the pipeline.
     */
    
    public GetPipelineConfigByIdPipelineConfig pipelineConfig;
    public GetPipelineConfigByIdResponse withPipelineConfig(GetPipelineConfigByIdPipelineConfig pipelineConfig) {
        this.pipelineConfig = pipelineConfig;
        return this;
    }
    
    
    public Integer statusCode;
    public GetPipelineConfigByIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetPipelineConfigByIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetPipelineConfigByIdDefaultApplicationJSON getPipelineConfigByIdDefaultApplicationJSONObject;
    public GetPipelineConfigByIdResponse withGetPipelineConfigByIdDefaultApplicationJSONObject(GetPipelineConfigByIdDefaultApplicationJSON getPipelineConfigByIdDefaultApplicationJSONObject) {
        this.getPipelineConfigByIdDefaultApplicationJSONObject = getPipelineConfigByIdDefaultApplicationJSONObject;
        return this;
    }
    
    public GetPipelineConfigByIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
