/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetProjectWorkflowMetricsRequest {
    /**
     * Whether to retrieve data for all branches combined. Use either this parameter OR the branch name parameter.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=all-branches")
    public Boolean allBranches;
    public GetProjectWorkflowMetricsRequest withAllBranches(Boolean allBranches) {
        this.allBranches = allBranches;
        return this;
    }
    
    /**
     * The name of a vcs branch. If not passed we will scope the API call to the default branch.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=branch")
    public String branch;
    public GetProjectWorkflowMetricsRequest withBranch(String branch) {
        this.branch = branch;
        return this;
    }
    
    /**
     * A token to retrieve the next page of results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page-token")
    public String pageToken;
    public GetProjectWorkflowMetricsRequest withPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
    }
    
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=project-slug")
    public String projectSlug;
    public GetProjectWorkflowMetricsRequest withProjectSlug(String projectSlug) {
        this.projectSlug = projectSlug;
        return this;
    }
    
    /**
     * The time window used to calculate summary metrics.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reporting-window")
    public GetProjectWorkflowMetricsReportingWindowEnum reportingWindow;
    public GetProjectWorkflowMetricsRequest withReportingWindow(GetProjectWorkflowMetricsReportingWindowEnum reportingWindow) {
        this.reportingWindow = reportingWindow;
        return this;
    }
    
    public GetProjectWorkflowMetricsRequest(@JsonProperty("project-slug") String projectSlug) {
        this.projectSlug = projectSlug;
  }
}
