/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetProjectBySlugProjectVcsInfo - Information about the VCS that hosts the project source code.
 */
public class GetProjectBySlugProjectVcsInfo {
    @JsonProperty("default_branch")
    public String defaultBranch;

    public GetProjectBySlugProjectVcsInfo withDefaultBranch(String defaultBranch) {
        this.defaultBranch = defaultBranch;
        return this;
    }
    
    /**
     * The VCS provider
     */
    @JsonProperty("provider")
    public GetProjectBySlugProjectVcsInfoProvider provider;

    public GetProjectBySlugProjectVcsInfo withProvider(GetProjectBySlugProjectVcsInfoProvider provider) {
        this.provider = provider;
        return this;
    }
    
    /**
     * URL to the repository hosting the project's code
     */
    @JsonProperty("vcs_url")
    public String vcsUrl;

    public GetProjectBySlugProjectVcsInfo withVcsUrl(String vcsUrl) {
        this.vcsUrl = vcsUrl;
        return this;
    }
    
    public GetProjectBySlugProjectVcsInfo(@JsonProperty("default_branch") String defaultBranch, @JsonProperty("provider") GetProjectBySlugProjectVcsInfoProvider provider, @JsonProperty("vcs_url") String vcsUrl) {
        this.defaultBranch = defaultBranch;
        this.provider = provider;
        this.vcsUrl = vcsUrl;
  }
}
