/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetPipelineByIdResponse {
    
    public String contentType;
    public GetPipelineByIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A pipeline object.
     */
    
    public GetPipelineByIdPipeline pipeline;
    public GetPipelineByIdResponse withPipeline(GetPipelineByIdPipeline pipeline) {
        this.pipeline = pipeline;
        return this;
    }
    
    
    public Integer statusCode;
    public GetPipelineByIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetPipelineByIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetPipelineByIdDefaultApplicationJSON getPipelineByIdDefaultApplicationJSONObject;
    public GetPipelineByIdResponse withGetPipelineByIdDefaultApplicationJSONObject(GetPipelineByIdDefaultApplicationJSON getPipelineByIdDefaultApplicationJSONObject) {
        this.getPipelineByIdDefaultApplicationJSONObject = getPipelineByIdDefaultApplicationJSONObject;
        return this;
    }
    
    public GetPipelineByIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
