/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests {
    /**
     * The class the test belongs to.
     */
    @JsonProperty("classname")
    public String classname;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withClassname(String classname) {
        this.classname = classname;
        return this;
    }
    
    /**
     * The number of times the test failed
     */
    @JsonProperty("failed_runs")
    public Long failedRuns;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withFailedRuns(Long failedRuns) {
        this.failedRuns = failedRuns;
        return this;
    }
    
    /**
     * The file the test belongs to.
     */
    @JsonProperty("file")
    public String file;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withFile(String file) {
        this.file = file;
        return this;
    }
    
    /**
     * Whether the test is flaky.
     */
    @JsonProperty("flaky")
    public Boolean flaky;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withFlaky(Boolean flaky) {
        this.flaky = flaky;
        return this;
    }
    
    /**
     * The name of the job.
     */
    @JsonProperty("job_name")
    public String jobName;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withJobName(String jobName) {
        this.jobName = jobName;
        return this;
    }
    
    /**
     * The 95th percentile duration, in seconds, among a group of test runs.
     */
    @JsonProperty("p95_duration")
    public Double p95Duration;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withP95Duration(Double p95Duration) {
        this.p95Duration = p95Duration;
        return this;
    }
    
    /**
     * The source of the test.
     */
    @JsonProperty("source")
    public String source;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withSource(String source) {
        this.source = source;
        return this;
    }
    
    /**
     * The name of the test.
     */
    @JsonProperty("test_name")
    public String testName;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withTestName(String testName) {
        this.testName = testName;
        return this;
    }
    
    /**
     * The total number of times the test was run.
     */
    @JsonProperty("total_runs")
    public Long totalRuns;
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests withTotalRuns(Long totalRuns) {
        this.totalRuns = totalRuns;
        return this;
    }
    
    public GetProjectWorkflowTestMetrics200ApplicationJSONSlowestTests(@JsonProperty("classname") String classname, @JsonProperty("failed_runs") Long failedRuns, @JsonProperty("file") String file, @JsonProperty("flaky") Boolean flaky, @JsonProperty("job_name") String jobName, @JsonProperty("p95_duration") Double p95Duration, @JsonProperty("source") String source, @JsonProperty("test_name") String testName, @JsonProperty("total_runs") Long totalRuns) {
        this.classname = classname;
        this.failedRuns = failedRuns;
        this.file = file;
        this.flaky = flaky;
        this.jobName = jobName;
        this.p95Duration = p95Duration;
        this.source = source;
        this.testName = testName;
        this.totalRuns = totalRuns;
  }
}
