/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics - Metrics relating to a workflow job's runs.
 */
public class GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics {
    /**
     * Metrics relating to the duration of runs for a workflow job.
     */
    @JsonProperty("duration_metrics")
    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetricsDurationMetrics durationMetrics;

    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics withDurationMetrics(GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetricsDurationMetrics durationMetrics) {
        this.durationMetrics = durationMetrics;
        return this;
    }
    
    /**
     * The number of failed runs.
     */
    @JsonProperty("failed_runs")
    public Long failedRuns;

    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics withFailedRuns(Long failedRuns) {
        this.failedRuns = failedRuns;
        return this;
    }
    
    @JsonProperty("success_rate")
    public Float successRate;

    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics withSuccessRate(Float successRate) {
        this.successRate = successRate;
        return this;
    }
    
    /**
     * The number of successful runs.
     */
    @JsonProperty("successful_runs")
    public Long successfulRuns;

    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics withSuccessfulRuns(Long successfulRuns) {
        this.successfulRuns = successfulRuns;
        return this;
    }
    
    /**
     * The average number of runs per day.
     */
    @JsonProperty("throughput")
    public Float throughput;

    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics withThroughput(Float throughput) {
        this.throughput = throughput;
        return this;
    }
    
    /**
     * The total credits consumed by the job in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
     */
    @JsonProperty("total_credits_used")
    public Long totalCreditsUsed;

    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics withTotalCreditsUsed(Long totalCreditsUsed) {
        this.totalCreditsUsed = totalCreditsUsed;
        return this;
    }
    
    /**
     * The total number of runs.
     */
    @JsonProperty("total_runs")
    public Long totalRuns;

    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics withTotalRuns(Long totalRuns) {
        this.totalRuns = totalRuns;
        return this;
    }
    
    public GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetrics(@JsonProperty("duration_metrics") GetProjectWorkflowJobMetrics200ApplicationJSONItemsMetricsDurationMetrics durationMetrics, @JsonProperty("failed_runs") Long failedRuns, @JsonProperty("success_rate") Float successRate, @JsonProperty("successful_runs") Long successfulRuns, @JsonProperty("throughput") Float throughput, @JsonProperty("total_credits_used") Long totalCreditsUsed, @JsonProperty("total_runs") Long totalRuns) {
        this.durationMetrics = durationMetrics;
        this.failedRuns = failedRuns;
        this.successRate = successRate;
        this.successfulRuns = successfulRuns;
        this.throughput = throughput;
        this.totalCreditsUsed = totalCreditsUsed;
        this.totalRuns = totalRuns;
  }
}
