/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetProjectBySlugProjectVcsInfoProvider - The VCS provider
 */
public enum GetProjectBySlugProjectVcsInfoProvider {
    BITBUCKET("Bitbucket"),
    CIRCLE_CI("CircleCI"),
    GIT_HUB("GitHub");

    @JsonValue
    public final String value;

    private GetProjectBySlugProjectVcsInfoProvider(String value) {
        this.value = value;
    }
}
