/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetPipelineByNumberResponse {
    
    public String contentType;

    public GetPipelineByNumberResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A pipeline object.
     */
    
    public GetPipelineByNumberPipeline pipeline;

    public GetPipelineByNumberResponse withPipeline(GetPipelineByNumberPipeline pipeline) {
        this.pipeline = pipeline;
        return this;
    }
    
    
    public Integer statusCode;

    public GetPipelineByNumberResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetPipelineByNumberResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetPipelineByNumberDefaultApplicationJSON getPipelineByNumberDefaultApplicationJSONObject;

    public GetPipelineByNumberResponse withGetPipelineByNumberDefaultApplicationJSONObject(GetPipelineByNumberDefaultApplicationJSON getPipelineByNumberDefaultApplicationJSONObject) {
        this.getPipelineByNumberDefaultApplicationJSONObject = getPipelineByNumberDefaultApplicationJSONObject;
        return this;
    }
    
    public GetPipelineByNumberResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
