/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.DateTimeDeserializer;
import DrevOps.CircleCi.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * GetPipelineByNumberPipeline - A pipeline response.
 */
public class GetPipelineByNumberPipeline {
    /**
     * The date and time the pipeline was created.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created_at")
    public OffsetDateTime createdAt;

    public GetPipelineByNumberPipeline withCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * A sequence of errors that have occurred within the pipeline.
     */
    @JsonProperty("errors")
    public GetPipelineByNumberPipelineErrors[] errors;

    public GetPipelineByNumberPipeline withErrors(GetPipelineByNumberPipelineErrors[] errors) {
        this.errors = errors;
        return this;
    }
    
    /**
     * The unique ID of the pipeline.
     */
    @JsonProperty("id")
    public String id;

    public GetPipelineByNumberPipeline withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The number of the pipeline.
     */
    @JsonProperty("number")
    public Long number;

    public GetPipelineByNumberPipeline withNumber(Long number) {
        this.number = number;
        return this;
    }
    
    /**
     * The project-slug for the pipeline.
     */
    @JsonProperty("project_slug")
    public String projectSlug;

    public GetPipelineByNumberPipeline withProjectSlug(String projectSlug) {
        this.projectSlug = projectSlug;
        return this;
    }
    
    /**
     * The current state of the pipeline.
     */
    @JsonProperty("state")
    public GetPipelineByNumberPipelineStateEnum state;

    public GetPipelineByNumberPipeline withState(GetPipelineByNumberPipelineStateEnum state) {
        this.state = state;
        return this;
    }
    
    /**
     * A summary of the trigger.
     */
    @JsonProperty("trigger")
    public GetPipelineByNumberPipelineTrigger trigger;

    public GetPipelineByNumberPipeline withTrigger(GetPipelineByNumberPipelineTrigger trigger) {
        this.trigger = trigger;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("trigger_parameters")
    public java.util.Map<String, Object> triggerParameters;

    public GetPipelineByNumberPipeline withTriggerParameters(java.util.Map<String, Object> triggerParameters) {
        this.triggerParameters = triggerParameters;
        return this;
    }
    
    /**
     * The date and time the pipeline was last updated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated_at")
    public OffsetDateTime updatedAt;

    public GetPipelineByNumberPipeline withUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    /**
     * VCS information for the pipeline.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vcs")
    public GetPipelineByNumberPipelineVcs vcs;

    public GetPipelineByNumberPipeline withVcs(GetPipelineByNumberPipelineVcs vcs) {
        this.vcs = vcs;
        return this;
    }
    
    public GetPipelineByNumberPipeline(@JsonProperty("created_at") OffsetDateTime createdAt, @JsonProperty("errors") GetPipelineByNumberPipelineErrors[] errors, @JsonProperty("id") String id, @JsonProperty("number") Long number, @JsonProperty("project_slug") String projectSlug, @JsonProperty("state") GetPipelineByNumberPipelineStateEnum state, @JsonProperty("trigger") GetPipelineByNumberPipelineTrigger trigger) {
        this.createdAt = createdAt;
        this.errors = errors;
        this.id = id;
        this.number = number;
        this.projectSlug = projectSlug;
        this.state = state;
        this.trigger = trigger;
  }
}
