/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetScheduleByIdScheduleTimetable2DaysOfWeek - Day in a week, in three letters format
 */
public enum GetScheduleByIdScheduleTimetable2DaysOfWeek {
    TUE("TUE"),
    SAT("SAT"),
    SUN("SUN"),
    MON("MON"),
    THU("THU"),
    WED("WED"),
    FRI("FRI");

    @JsonValue
    public final String value;

    private GetScheduleByIdScheduleTimetable2DaysOfWeek(String value) {
        this.value = value;
    }
}
