/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetScheduleByIdResponse {
    
    public String contentType;
    public GetScheduleByIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A schedule object.
     */
    
    public GetScheduleByIdSchedule schedule;
    public GetScheduleByIdResponse withSchedule(GetScheduleByIdSchedule schedule) {
        this.schedule = schedule;
        return this;
    }
    
    
    public Integer statusCode;
    public GetScheduleByIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetScheduleByIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetScheduleByIdDefaultApplicationJSON getScheduleByIdDefaultApplicationJSONObject;
    public GetScheduleByIdResponse withGetScheduleByIdDefaultApplicationJSONObject(GetScheduleByIdDefaultApplicationJSON getScheduleByIdDefaultApplicationJSONObject) {
        this.getScheduleByIdDefaultApplicationJSONObject = getScheduleByIdDefaultApplicationJSONObject;
        return this;
    }
    
    public GetScheduleByIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
