/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class GetTestsTestsResponseItems {
    /**
     * The programmatic location of the test.
     */
    @JsonProperty("classname")
    public String classname;

    public GetTestsTestsResponseItems withClassname(String classname) {
        this.classname = classname;
        return this;
    }
    
    /**
     * The file in which the test is defined.
     */
    @JsonProperty("file")
    public String file;

    public GetTestsTestsResponseItems withFile(String file) {
        this.file = file;
        return this;
    }
    
    /**
     * The failure message associated with the test.
     */
    @JsonProperty("message")
    public String message;

    public GetTestsTestsResponseItems withMessage(String message) {
        this.message = message;
        return this;
    }
    
    /**
     * The name of the test.
     */
    @JsonProperty("name")
    public String name;

    public GetTestsTestsResponseItems withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Indication of whether the test succeeded.
     */
    @JsonProperty("result")
    public String result;

    public GetTestsTestsResponseItems withResult(String result) {
        this.result = result;
        return this;
    }
    
    /**
     * The time it took to run the test in seconds
     */
    @JsonProperty("run_time")
    public Double runTime;

    public GetTestsTestsResponseItems withRunTime(Double runTime) {
        this.runTime = runTime;
        return this;
    }
    
    /**
     * The program that generated the test results
     */
    @JsonProperty("source")
    public String source;

    public GetTestsTestsResponseItems withSource(String source) {
        this.source = source;
        return this;
    }
    
    public GetTestsTestsResponseItems(@JsonProperty("classname") String classname, @JsonProperty("file") String file, @JsonProperty("message") String message, @JsonProperty("name") String name, @JsonProperty("result") String result, @JsonProperty("run_time") Double runTime, @JsonProperty("source") String source) {
        this.classname = classname;
        this.file = file;
        this.message = message;
        this.name = name;
        this.result = result;
        this.runTime = runTime;
        this.source = source;
  }
}
