/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetTestsResponse {
    
    public String contentType;
    public GetTestsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetTestsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetTestsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A paginated list of test results.
     */
    
    public GetTestsTestsResponse testsResponse;
    public GetTestsResponse withTestsResponse(GetTestsTestsResponse testsResponse) {
        this.testsResponse = testsResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetTestsDefaultApplicationJSON getTestsDefaultApplicationJSONObject;
    public GetTestsResponse withGetTestsDefaultApplicationJSONObject(GetTestsDefaultApplicationJSON getTestsDefaultApplicationJSONObject) {
        this.getTestsDefaultApplicationJSONObject = getTestsDefaultApplicationJSONObject;
        return this;
    }
    
    public GetTestsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
