/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetUserResponse {
    
    public String contentType;
    public GetUserResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetUserResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetUserResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * User login information.
     */
    
    public GetUserUser user;
    public GetUserResponse withUser(GetUserUser user) {
        this.user = user;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetUserDefaultApplicationJSON getUserDefaultApplicationJSONObject;
    public GetUserResponse withGetUserDefaultApplicationJSONObject(GetUserDefaultApplicationJSON getUserDefaultApplicationJSONObject) {
        this.getUserDefaultApplicationJSONObject = getUserDefaultApplicationJSONObject;
        return this;
    }
    
    public GetUserResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
