/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetUserRequest {
    /**
     * The unique ID of the user.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;
    public GetUserRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public GetUserRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
