/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetWebhookByIdResponse {
    
    public String contentType;

    public GetWebhookByIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetWebhookByIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetWebhookByIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A webhook
     */
    
    public GetWebhookByIdWebhook webhook;

    public GetWebhookByIdResponse withWebhook(GetWebhookByIdWebhook webhook) {
        this.webhook = webhook;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetWebhookByIdDefaultApplicationJSON getWebhookByIdDefaultApplicationJSONObject;

    public GetWebhookByIdResponse withGetWebhookByIdDefaultApplicationJSONObject(GetWebhookByIdDefaultApplicationJSON getWebhookByIdDefaultApplicationJSONObject) {
        this.getWebhookByIdDefaultApplicationJSONObject = getWebhookByIdDefaultApplicationJSONObject;
        return this;
    }
    
    public GetWebhookByIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
