/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetWorkflowSummary200ApplicationJSON - Workflow level aggregated metrics and trends response
 */
public class GetWorkflowSummary200ApplicationJSON {
    /**
     * Metrics aggregated across a workflow for a given time window.
     */
    @JsonProperty("metrics")
    public GetWorkflowSummary200ApplicationJSONMetrics metrics;
    public GetWorkflowSummary200ApplicationJSON withMetrics(GetWorkflowSummary200ApplicationJSONMetrics metrics) {
        this.metrics = metrics;
        return this;
    }
    
    /**
     * Trends for aggregated metrics across a workflow for a given time window.
     */
    @JsonProperty("trends")
    public GetWorkflowSummary200ApplicationJSONTrends trends;
    public GetWorkflowSummary200ApplicationJSON withTrends(GetWorkflowSummary200ApplicationJSONTrends trends) {
        this.trends = trends;
        return this;
    }
    
    /**
     * A list of all the workflow names for a given project.
     */
    @JsonProperty("workflow_names")
    public String[] workflowNames;
    public GetWorkflowSummary200ApplicationJSON withWorkflowNames(String[] workflowNames) {
        this.workflowNames = workflowNames;
        return this;
    }
    
    public GetWorkflowSummary200ApplicationJSON(@JsonProperty("metrics") GetWorkflowSummary200ApplicationJSONMetrics metrics, @JsonProperty("trends") GetWorkflowSummary200ApplicationJSONTrends trends, @JsonProperty("workflow_names") String[] workflowNames) {
        this.metrics = metrics;
        this.trends = trends;
        this.workflowNames = workflowNames;
  }
}
