/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetWorkflowByIdWorkflowTag - Tag used for the workflow
 */
public enum GetWorkflowByIdWorkflowTag {
    SETUP("setup");

    @JsonValue
    public final String value;

    private GetWorkflowByIdWorkflowTag(String value) {
        this.value = value;
    }
}
