/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetWebhooksRequest {
    /**
     * ID of the scope being used (at the moment, only project ID is supported)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scope-id")
    public String scopeId;

    public GetWebhooksRequest withScopeId(String scopeId) {
        this.scopeId = scopeId;
        return this;
    }
    
    /**
     * Type of the scope being used
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scope-type")
    public GetWebhooksScopeType scopeType;

    public GetWebhooksRequest withScopeType(GetWebhooksScopeType scopeType) {
        this.scopeType = scopeType;
        return this;
    }
    
    public GetWebhooksRequest(@JsonProperty("scope-id") String scopeId, @JsonProperty("scope-type") GetWebhooksScopeType scopeType) {
        this.scopeId = scopeId;
        this.scopeType = scopeType;
  }
}
