/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;



/**
 * GetWorkflowSummaryBranches - The names of VCS branches to include in branch-level workflow metrics.
 */
public class GetWorkflowSummaryBranches {
    public GetWorkflowSummaryBranches(){}
}
