/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetWorkflowSummaryResponse {
    
    public String contentType;

    public GetWorkflowSummaryResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetWorkflowSummaryResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetWorkflowSummaryResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Metrics and trends for a workflow
     */
    
    public GetWorkflowSummary200ApplicationJSON getWorkflowSummary200ApplicationJSONObject;

    public GetWorkflowSummaryResponse withGetWorkflowSummary200ApplicationJSONObject(GetWorkflowSummary200ApplicationJSON getWorkflowSummary200ApplicationJSONObject) {
        this.getWorkflowSummary200ApplicationJSONObject = getWorkflowSummary200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public GetWorkflowSummaryDefaultApplicationJSON getWorkflowSummaryDefaultApplicationJSONObject;

    public GetWorkflowSummaryResponse withGetWorkflowSummaryDefaultApplicationJSONObject(GetWorkflowSummaryDefaultApplicationJSON getWorkflowSummaryDefaultApplicationJSONObject) {
        this.getWorkflowSummaryDefaultApplicationJSONObject = getWorkflowSummaryDefaultApplicationJSONObject;
        return this;
    }
    
    public GetWorkflowSummaryResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
