/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.DateTimeDeserializer;
import DrevOps.CircleCi.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

/**
 * GetWorkflowSummary200ApplicationJSONMetrics - Metrics aggregated across a workflow for a given time window.
 */
public class GetWorkflowSummary200ApplicationJSONMetrics {
    /**
     * Metrics relating to the duration of runs for a workflow.
     */
    @JsonProperty("duration_metrics")
    public GetWorkflowSummary200ApplicationJSONMetricsDurationMetrics durationMetrics;

    public GetWorkflowSummary200ApplicationJSONMetrics withDurationMetrics(GetWorkflowSummary200ApplicationJSONMetricsDurationMetrics durationMetrics) {
        this.durationMetrics = durationMetrics;
        return this;
    }
    
    /**
     * The number of failed runs.
     */
    @JsonProperty("failed_runs")
    public Long failedRuns;

    public GetWorkflowSummary200ApplicationJSONMetrics withFailedRuns(Long failedRuns) {
        this.failedRuns = failedRuns;
        return this;
    }
    
    /**
     * The mean time to recovery (mean time between failures and their next success) in seconds.
     */
    @JsonProperty("mttr")
    public Long mttr;

    public GetWorkflowSummary200ApplicationJSONMetrics withMttr(Long mttr) {
        this.mttr = mttr;
        return this;
    }
    
    @JsonProperty("success_rate")
    public Float successRate;

    public GetWorkflowSummary200ApplicationJSONMetrics withSuccessRate(Float successRate) {
        this.successRate = successRate;
        return this;
    }
    
    /**
     * The number of successful runs.
     */
    @JsonProperty("successful_runs")
    public Long successfulRuns;

    public GetWorkflowSummary200ApplicationJSONMetrics withSuccessfulRuns(Long successfulRuns) {
        this.successfulRuns = successfulRuns;
        return this;
    }
    
    /**
     * The average number of runs per day.
     */
    @JsonProperty("throughput")
    public Float throughput;

    public GetWorkflowSummary200ApplicationJSONMetrics withThroughput(Float throughput) {
        this.throughput = throughput;
        return this;
    }
    
    /**
     * The total credits consumed by the workflow in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
     */
    @JsonProperty("total_credits_used")
    public Long totalCreditsUsed;

    public GetWorkflowSummary200ApplicationJSONMetrics withTotalCreditsUsed(Long totalCreditsUsed) {
        this.totalCreditsUsed = totalCreditsUsed;
        return this;
    }
    
    /**
     * The total number of runs.
     */
    @JsonProperty("total_runs")
    public Long totalRuns;

    public GetWorkflowSummary200ApplicationJSONMetrics withTotalRuns(Long totalRuns) {
        this.totalRuns = totalRuns;
        return this;
    }
    
    /**
     * The end of the aggregation window for workflow metrics.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("window_end")
    public OffsetDateTime windowEnd;

    public GetWorkflowSummary200ApplicationJSONMetrics withWindowEnd(OffsetDateTime windowEnd) {
        this.windowEnd = windowEnd;
        return this;
    }
    
    /**
     * The start of the aggregation window for workflow metrics.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("window_start")
    public OffsetDateTime windowStart;

    public GetWorkflowSummary200ApplicationJSONMetrics withWindowStart(OffsetDateTime windowStart) {
        this.windowStart = windowStart;
        return this;
    }
    
    public GetWorkflowSummary200ApplicationJSONMetrics(@JsonProperty("duration_metrics") GetWorkflowSummary200ApplicationJSONMetricsDurationMetrics durationMetrics, @JsonProperty("failed_runs") Long failedRuns, @JsonProperty("mttr") Long mttr, @JsonProperty("success_rate") Float successRate, @JsonProperty("successful_runs") Long successfulRuns, @JsonProperty("throughput") Float throughput, @JsonProperty("total_credits_used") Long totalCreditsUsed, @JsonProperty("total_runs") Long totalRuns, @JsonProperty("window_end") OffsetDateTime windowEnd, @JsonProperty("window_start") OffsetDateTime windowStart) {
        this.durationMetrics = durationMetrics;
        this.failedRuns = failedRuns;
        this.mttr = mttr;
        this.successRate = successRate;
        this.successfulRuns = successfulRuns;
        this.throughput = throughput;
        this.totalCreditsUsed = totalCreditsUsed;
        this.totalRuns = totalRuns;
        this.windowEnd = windowEnd;
        this.windowStart = windowStart;
  }
}
