/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListEnvironmentVariablesFromContextResponse {
    
    public String contentType;
    public ListEnvironmentVariablesFromContextResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ListEnvironmentVariablesFromContextResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListEnvironmentVariablesFromContextResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A paginated list of environment variables
     */
    
    public ListEnvironmentVariablesFromContext200ApplicationJSON listEnvironmentVariablesFromContext200ApplicationJSONObject;
    public ListEnvironmentVariablesFromContextResponse withListEnvironmentVariablesFromContext200ApplicationJSONObject(ListEnvironmentVariablesFromContext200ApplicationJSON listEnvironmentVariablesFromContext200ApplicationJSONObject) {
        this.listEnvironmentVariablesFromContext200ApplicationJSONObject = listEnvironmentVariablesFromContext200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public ListEnvironmentVariablesFromContextDefaultApplicationJSON listEnvironmentVariablesFromContextDefaultApplicationJSONObject;
    public ListEnvironmentVariablesFromContextResponse withListEnvironmentVariablesFromContextDefaultApplicationJSONObject(ListEnvironmentVariablesFromContextDefaultApplicationJSON listEnvironmentVariablesFromContextDefaultApplicationJSONObject) {
        this.listEnvironmentVariablesFromContextDefaultApplicationJSONObject = listEnvironmentVariablesFromContextDefaultApplicationJSONObject;
        return this;
    }
    
    public ListEnvironmentVariablesFromContextResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
