/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListCheckoutKeysCheckoutKeyListResponse - A sequence of checkout keys.
 */
public class ListCheckoutKeysCheckoutKeyListResponse {
    @JsonProperty("items")
    public ListCheckoutKeysCheckoutKeyListResponseCheckoutKey[] items;

    public ListCheckoutKeysCheckoutKeyListResponse withItems(ListCheckoutKeysCheckoutKeyListResponseCheckoutKey[] items) {
        this.items = items;
        return this;
    }
    
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     */
    @JsonProperty("next_page_token")
    public String nextPageToken;

    public ListCheckoutKeysCheckoutKeyListResponse withNextPageToken(String nextPageToken) {
        this.nextPageToken = nextPageToken;
        return this;
    }
    
    public ListCheckoutKeysCheckoutKeyListResponse(@JsonProperty("items") ListCheckoutKeysCheckoutKeyListResponseCheckoutKey[] items, @JsonProperty("next_page_token") String nextPageToken) {
        this.items = items;
        this.nextPageToken = nextPageToken;
  }
}
