/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListPipelinesForProjectResponse {
    
    public String contentType;
    public ListPipelinesForProjectResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A sequence of pipelines.
     */
    
    public ListPipelinesForProjectPipelineListResponse pipelineListResponse;
    public ListPipelinesForProjectResponse withPipelineListResponse(ListPipelinesForProjectPipelineListResponse pipelineListResponse) {
        this.pipelineListResponse = pipelineListResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public ListPipelinesForProjectResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListPipelinesForProjectResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public ListPipelinesForProjectDefaultApplicationJSON listPipelinesForProjectDefaultApplicationJSONObject;
    public ListPipelinesForProjectResponse withListPipelinesForProjectDefaultApplicationJSONObject(ListPipelinesForProjectDefaultApplicationJSON listPipelinesForProjectDefaultApplicationJSONObject) {
        this.listPipelinesForProjectDefaultApplicationJSONObject = listPipelinesForProjectDefaultApplicationJSONObject;
        return this;
    }
    
    public ListPipelinesForProjectResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
