/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListSchedulesForProjectResponse {
    
    public String contentType;
    public ListSchedulesForProjectResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public ListSchedulesForProjectResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public ListSchedulesForProjectResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A sequence of schedules.
     */
    
    public ListSchedulesForProject200ApplicationJSON listSchedulesForProject200ApplicationJSONObject;
    public ListSchedulesForProjectResponse withListSchedulesForProject200ApplicationJSONObject(ListSchedulesForProject200ApplicationJSON listSchedulesForProject200ApplicationJSONObject) {
        this.listSchedulesForProject200ApplicationJSONObject = listSchedulesForProject200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public ListSchedulesForProjectDefaultApplicationJSON listSchedulesForProjectDefaultApplicationJSONObject;
    public ListSchedulesForProjectResponse withListSchedulesForProjectDefaultApplicationJSONObject(ListSchedulesForProjectDefaultApplicationJSON listSchedulesForProjectDefaultApplicationJSONObject) {
        this.listSchedulesForProjectDefaultApplicationJSONObject = listSchedulesForProjectDefaultApplicationJSONObject;
        return this;
    }
    
    public ListSchedulesForProjectResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
