/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import DrevOps.CircleCi.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ListWorkflowsByPipelineIdRequest {
    /**
     * A token to retrieve the next page of results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page-token")
    public String pageToken;

    public ListWorkflowsByPipelineIdRequest withPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
    }
    
    /**
     * The unique ID of the pipeline.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=pipeline-id")
    public String pipelineId;

    public ListWorkflowsByPipelineIdRequest withPipelineId(String pipelineId) {
        this.pipelineId = pipelineId;
        return this;
    }
    
    public ListWorkflowsByPipelineIdRequest(@JsonProperty("pipeline-id") String pipelineId) {
        this.pipelineId = pipelineId;
  }
}
