/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListSchedulesForProject200ApplicationJSON - A sequence of schedules
 */
public class ListSchedulesForProject200ApplicationJSON {
    @JsonProperty("items")
    public ListSchedulesForProject200ApplicationJSONSchedule[] items;
    public ListSchedulesForProject200ApplicationJSON withItems(ListSchedulesForProject200ApplicationJSONSchedule[] items) {
        this.items = items;
        return this;
    }
    
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     */
    @JsonProperty("next_page_token")
    public String nextPageToken;
    public ListSchedulesForProject200ApplicationJSON withNextPageToken(String nextPageToken) {
        this.nextPageToken = nextPageToken;
        return this;
    }
    
    public ListSchedulesForProject200ApplicationJSON(@JsonProperty("items") ListSchedulesForProject200ApplicationJSONSchedule[] items, @JsonProperty("next_page_token") String nextPageToken) {
        this.items = items;
        this.nextPageToken = nextPageToken;
  }
}
