/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListPipelinesPipelineListResponsePipelineErrors - An error with a type and message.
 */
public class ListPipelinesPipelineListResponsePipelineErrors {
    /**
     * A human-readable error message.
     */
    @JsonProperty("message")
    public String message;

    public ListPipelinesPipelineListResponsePipelineErrors withMessage(String message) {
        this.message = message;
        return this;
    }
    
    /**
     * The type of error.
     */
    @JsonProperty("type")
    public ListPipelinesPipelineListResponsePipelineErrorsType type;

    public ListPipelinesPipelineListResponsePipelineErrors withType(ListPipelinesPipelineListResponsePipelineErrorsType type) {
        this.type = type;
        return this;
    }
    
    public ListPipelinesPipelineListResponsePipelineErrors(@JsonProperty("message") String message, @JsonProperty("type") ListPipelinesPipelineListResponsePipelineErrorsType type) {
        this.message = message;
        this.type = type;
  }
}
