/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ListMyPipelinesPipelineListResponsePipelineTriggerTypeEnum - The type of trigger.
 */
public enum ListMyPipelinesPipelineListResponsePipelineTriggerTypeEnum {
    SCHEDULED_PIPELINE("scheduled_pipeline"),
    EXPLICIT("explicit"),
    API("api"),
    WEBHOOK("webhook");

    @JsonValue
    public final String value;

    private ListMyPipelinesPipelineListResponsePipelineTriggerTypeEnum(String value) {
        this.value = value;
    }
}
