/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListMyPipelinesResponse {
    
    public String contentType;

    public ListMyPipelinesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A sequence of pipelines.
     */
    
    public ListMyPipelinesPipelineListResponse pipelineListResponse;

    public ListMyPipelinesResponse withPipelineListResponse(ListMyPipelinesPipelineListResponse pipelineListResponse) {
        this.pipelineListResponse = pipelineListResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ListMyPipelinesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListMyPipelinesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public ListMyPipelinesDefaultApplicationJSON listMyPipelinesDefaultApplicationJSONObject;

    public ListMyPipelinesResponse withListMyPipelinesDefaultApplicationJSONObject(ListMyPipelinesDefaultApplicationJSON listMyPipelinesDefaultApplicationJSONObject) {
        this.listMyPipelinesDefaultApplicationJSONObject = listMyPipelinesDefaultApplicationJSONObject;
        return this;
    }
    
    public ListMyPipelinesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
