/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ListWorkflowJobsWorkflowJobListResponseJobTypeEnum - The type of job.
 */
public enum ListWorkflowJobsWorkflowJobListResponseJobTypeEnum {
    BUILD("build"),
    APPROVAL("approval");

    @JsonValue
    public final String value;

    private ListWorkflowJobsWorkflowJobListResponseJobTypeEnum(String value) {
        this.value = value;
    }
}
