/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListWorkflowJobsWorkflowJobListResponse - A paginated sequence of jobs.
 */
public class ListWorkflowJobsWorkflowJobListResponse {
    @JsonProperty("items")
    public ListWorkflowJobsWorkflowJobListResponseJob[] items;

    public ListWorkflowJobsWorkflowJobListResponse withItems(ListWorkflowJobsWorkflowJobListResponseJob[] items) {
        this.items = items;
        return this;
    }
    
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     */
    @JsonProperty("next_page_token")
    public String nextPageToken;

    public ListWorkflowJobsWorkflowJobListResponse withNextPageToken(String nextPageToken) {
        this.nextPageToken = nextPageToken;
        return this;
    }
    
    public ListWorkflowJobsWorkflowJobListResponse(@JsonProperty("items") ListWorkflowJobsWorkflowJobListResponseJob[] items, @JsonProperty("next_page_token") String nextPageToken) {
        this.items = items;
        this.nextPageToken = nextPageToken;
  }
}
