/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListContextsResponse {
    
    public String contentType;

    public ListContextsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ListContextsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListContextsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A paginated list of contexts
     */
    
    public ListContexts200ApplicationJSON listContexts200ApplicationJSONObject;

    public ListContextsResponse withListContexts200ApplicationJSONObject(ListContexts200ApplicationJSON listContexts200ApplicationJSONObject) {
        this.listContexts200ApplicationJSONObject = listContexts200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public ListContextsDefaultApplicationJSON listContextsDefaultApplicationJSONObject;

    public ListContextsResponse withListContextsDefaultApplicationJSONObject(ListContextsDefaultApplicationJSON listContextsDefaultApplicationJSONObject) {
        this.listContextsDefaultApplicationJSONObject = listContextsDefaultApplicationJSONObject;
        return this;
    }
    
    public ListContextsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
