/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListWorkflowsByPipelineIdResponse {
    
    public String contentType;

    public ListWorkflowsByPipelineIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ListWorkflowsByPipelineIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListWorkflowsByPipelineIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A paginated list of workflow objects.
     */
    
    public ListWorkflowsByPipelineIdWorkflowListResponse workflowListResponse;

    public ListWorkflowsByPipelineIdResponse withWorkflowListResponse(ListWorkflowsByPipelineIdWorkflowListResponse workflowListResponse) {
        this.workflowListResponse = workflowListResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public ListWorkflowsByPipelineIdDefaultApplicationJSON listWorkflowsByPipelineIdDefaultApplicationJSONObject;

    public ListWorkflowsByPipelineIdResponse withListWorkflowsByPipelineIdDefaultApplicationJSONObject(ListWorkflowsByPipelineIdDefaultApplicationJSON listWorkflowsByPipelineIdDefaultApplicationJSONObject) {
        this.listWorkflowsByPipelineIdDefaultApplicationJSONObject = listWorkflowsByPipelineIdDefaultApplicationJSONObject;
        return this;
    }
    
    public ListWorkflowsByPipelineIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
