/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListPipelinesResponse {
    
    public String contentType;

    public ListPipelinesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * A sequence of pipelines.
     */
    
    public ListPipelinesPipelineListResponse pipelineListResponse;

    public ListPipelinesResponse withPipelineListResponse(ListPipelinesPipelineListResponse pipelineListResponse) {
        this.pipelineListResponse = pipelineListResponse;
        return this;
    }
    
    
    public Integer statusCode;

    public ListPipelinesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListPipelinesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public ListPipelinesDefaultApplicationJSON listPipelinesDefaultApplicationJSONObject;

    public ListPipelinesResponse withListPipelinesDefaultApplicationJSONObject(ListPipelinesDefaultApplicationJSON listPipelinesDefaultApplicationJSONObject) {
        this.listPipelinesDefaultApplicationJSONObject = listPipelinesDefaultApplicationJSONObject;
        return this;
    }
    
    public ListPipelinesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
