/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListWorkflowsByPipelineIdWorkflowListResponse - A list of workflows and associated pagination token.
 */
public class ListWorkflowsByPipelineIdWorkflowListResponse {
    /**
     * A list of workflows.
     */
    @JsonProperty("items")
    public ListWorkflowsByPipelineIdWorkflowListResponseWorkflow[] items;

    public ListWorkflowsByPipelineIdWorkflowListResponse withItems(ListWorkflowsByPipelineIdWorkflowListResponseWorkflow[] items) {
        this.items = items;
        return this;
    }
    
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     */
    @JsonProperty("next_page_token")
    public String nextPageToken;

    public ListWorkflowsByPipelineIdWorkflowListResponse withNextPageToken(String nextPageToken) {
        this.nextPageToken = nextPageToken;
        return this;
    }
    
    public ListWorkflowsByPipelineIdWorkflowListResponse(@JsonProperty("items") ListWorkflowsByPipelineIdWorkflowListResponseWorkflow[] items, @JsonProperty("next_page_token") String nextPageToken) {
        this.items = items;
        this.nextPageToken = nextPageToken;
  }
}
