/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ListCheckoutKeysCheckoutKeyListResponseCheckoutKeyCheckoutKeyType - The type of checkout key. This may be either `deploy-key` or `github-user-key`.
 */
public enum ListCheckoutKeysCheckoutKeyListResponseCheckoutKeyCheckoutKeyType {
    DEPLOY_KEY("deploy-key"),
    GITHUB_USER_KEY("github-user-key");

    @JsonValue
    public final String value;

    private ListCheckoutKeysCheckoutKeyListResponseCheckoutKeyCheckoutKeyType(String value) {
        this.value = value;
    }
}
