/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListPipelinesForProjectPipelineListResponsePipelineErrors - An error with a type and message.
 */
public class ListPipelinesForProjectPipelineListResponsePipelineErrors {
    /**
     * A human-readable error message.
     */
    @JsonProperty("message")
    public String message;

    public ListPipelinesForProjectPipelineListResponsePipelineErrors withMessage(String message) {
        this.message = message;
        return this;
    }
    
    /**
     * The type of error.
     */
    @JsonProperty("type")
    public ListPipelinesForProjectPipelineListResponsePipelineErrorsTypeEnum type;

    public ListPipelinesForProjectPipelineListResponsePipelineErrors withType(ListPipelinesForProjectPipelineListResponsePipelineErrorsTypeEnum type) {
        this.type = type;
        return this;
    }
    
    public ListPipelinesForProjectPipelineListResponsePipelineErrors(@JsonProperty("message") String message, @JsonProperty("type") ListPipelinesForProjectPipelineListResponsePipelineErrorsTypeEnum type) {
        this.message = message;
        this.type = type;
  }
}
