/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListPipelinesForProjectPipelineListResponse - List of pipelines
 */
public class ListPipelinesForProjectPipelineListResponse {
    @JsonProperty("items")
    public ListPipelinesForProjectPipelineListResponsePipeline[] items;
    public ListPipelinesForProjectPipelineListResponse withItems(ListPipelinesForProjectPipelineListResponsePipeline[] items) {
        this.items = items;
        return this;
    }
    
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     */
    @JsonProperty("next_page_token")
    public String nextPageToken;
    public ListPipelinesForProjectPipelineListResponse withNextPageToken(String nextPageToken) {
        this.nextPageToken = nextPageToken;
        return this;
    }
    
    public ListPipelinesForProjectPipelineListResponse(@JsonProperty("items") ListPipelinesForProjectPipelineListResponsePipeline[] items, @JsonProperty("next_page_token") String nextPageToken) {
        this.items = items;
        this.nextPageToken = nextPageToken;
  }
}
