/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class RerunWorkflowResponse {
    
    public String contentType;
    public RerunWorkflowResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public RerunWorkflowResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public RerunWorkflowResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A confirmation message.
     */
    
    public RerunWorkflow202ApplicationJSON rerunWorkflow202ApplicationJSONObject;
    public RerunWorkflowResponse withRerunWorkflow202ApplicationJSONObject(RerunWorkflow202ApplicationJSON rerunWorkflow202ApplicationJSONObject) {
        this.rerunWorkflow202ApplicationJSONObject = rerunWorkflow202ApplicationJSONObject;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public RerunWorkflowDefaultApplicationJSON rerunWorkflowDefaultApplicationJSONObject;
    public RerunWorkflowResponse withRerunWorkflowDefaultApplicationJSONObject(RerunWorkflowDefaultApplicationJSON rerunWorkflowDefaultApplicationJSONObject) {
        this.rerunWorkflowDefaultApplicationJSONObject = rerunWorkflowDefaultApplicationJSONObject;
        return this;
    }
    
    public RerunWorkflowResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
