/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package DrevOps.CircleCi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class UpdateWebhookResponse {
    
    public String contentType;

    public UpdateWebhookResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateWebhookResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateWebhookResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * A webhook
     */
    
    public UpdateWebhookWebhook webhook;

    public UpdateWebhookResponse withWebhook(UpdateWebhookWebhook webhook) {
        this.webhook = webhook;
        return this;
    }
    
    /**
     * Error response.
     */
    
    public UpdateWebhookDefaultApplicationJSON updateWebhookDefaultApplicationJSONObject;

    public UpdateWebhookResponse withUpdateWebhookDefaultApplicationJSONObject(UpdateWebhookDefaultApplicationJSON updateWebhookDefaultApplicationJSONObject) {
        this.updateWebhookDefaultApplicationJSONObject = updateWebhookDefaultApplicationJSONObject;
        return this;
    }
    
    public UpdateWebhookResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
